name: store_futures
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider:
  state_notifier:
  modal_progress_hud:
  mobx:
  flutter_mobx:
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner:
  mobx_codegen:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
